#!/usr/bin/perl

use PApp::SQL;
use Coro::Event;

$PApp::SQL::DBH = PApp::SQL::connect_cached __FILE__, "DBI:mysql:myhttpd"
   or die "unable to connect to database";

$VERSION = 0.01;

$SIG{CHLD} = 'IGNORE';

require "config.pl";
require "netgeo.pl";
require "access.pl";
require "diridx.pl";
require "httpd.pl";
require "shell.pl";

loop;

if ($RESTART) {
   $_->close for @listen_sockets;
   fork && exec $0, @ARGV;
   loop(60*60);
}

print "myhttpd ended\n";#d#

