#!/opt/bin/perl

use EV;
use Coro::EV;
use Time::HiRes 'time';

$starttime = time;

$VERSION = 1.1;
$NAME = "myhttpd/$VERSION";
#$NAME = "Apache/1.3.19 (Unix)  (SuSE/Linux) PHP/4.0.4pl1 mod_ssl/2.8.1 OpenSSL/0.9.6";

$SIG{CHLD} = 'IGNORE';

require "config.pl";
require "misc.pl";
require "database.pl";
require "netgeo.pl";
require "err.pl";
require "access.pl";
require "queue.pl";
require "tbf.pl";
require "diridx.pl";
require "internal.pl";
require "httpd.pl";
require "shell.pl";

EV::loop;

if ($RESTART) {
   $_->close for @listen_sockets;
   fork && exec $0, @ARGV;

   my $finish = EV::timer 60*60, 0, sub { EV::unloop };
   EV::loop;
}

print "myhttpd ended\n";#d#

