#!/usr/bin/perl

use Coro::Event;

$SIG{CHLD} = 'IGNORE';

require "config.pl";
require "netgeo.pl";
require "access.pl";
require "httpd.pl";
require "shell.pl";

loop;

if ($RESTART) {
   $_->close for @listen_sockets;
   fork && exec $0, @ARGV;
   loop(60*60);
}

print "myhttpd ended\n";#d#

